PYTHON2 ?= $(shell pwd)/../../../venv3.7/bin/python
ESPIDF ?= $(shell pwd)/../../../esp-idf
BOARD ?= GENERIC
PORT ?= /dev/cu.usbserial-14210
FLASH_MODE ?= dio
FLASH_SIZE ?= 4MB
BAUD ?= 115200

include Makefile
